services:
  adguard:
    container_name: adguard
    image: adguard/adguardhome:v0.107.71
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "3000:3000/tcp"
    volumes:
      # AdGuard expect conf and work dirs, but we keep our dir. structure the same everywhere.
      - ./config:/opt/adguardhome/conf
      - ./data:/opt/adguardhome/work
    networks:
      - proxy_caddy
      - adguard_net
    labels:
      - "logging=promtail"
      - "service_name=adguard"
    healthcheck:
      test: [ "CMD-SHELL", "nslookup localhost 127.0.0.1 > /dev/null || exit 1" ]
      interval: 45s
      timeout: 10s
      retries: 3
      start_period: 20s
    cap_add:
      - NET_ADMIN
      - NET_RAW

  adguard-exporter:
    # No healthcheck, distroless/scratch.
    container_name: adguard-exporter
    image: ebrianne/adguard-exporter:v1.14
    restart: unless-stopped
    environment:
      - ADGUARD_PROTOCOL=http
      - ADGUARD_HOSTNAME=adguard
      - ADGUARD_PORT=3000
      - ADGUARD_USERNAME=${ADGUARD_USER}
      - ADGUARD_PASSWORD=${ADGUARD_PASSWORD}
      - INTERVAL=15s
    networks:
      - adguard_net
      - monitoring_net
    labels:
      - "logging=promtail"
      - "service_name=adguard-exporter"

networks:
  adguard_net:
    driver: bridge
    name: adguard_net
    external: true
  proxy_caddy:
    external: true
  monitoring_net:
    external: true
