services:
  adguard:
    container_name: adguard
    image: adguard/adguardhome:v0.107.71
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "3000:3000/tcp"
    volumes:
      # AdGuard expect conf and work dirs, but we keep our dir. structure the same everywhere.
      - ./config:/opt/adguardhome/conf
      - ./data:/opt/adguardhome/work
    networks:
      - proxy_caddy
    labels:
      - "logging=promtail"
      - "service_name=adguard"
    healthcheck:
      test: [ "CMD-SHELL", "nslookup localhost 127.0.0.1 > /dev/null || exit 1" ]
      interval: 45s
      timeout: 10s
      retries: 3
      start_period: 20s
    cap_add:
      - NET_ADMIN
      - NET_RAW

networks:
  proxy_caddy:
    external: true
